### ISSUE TITLE
No script named 'networkmgr'

### ISSUE THREAD

**Issue by jjess** [GhostBSD/networkmgr#13]
After fresh git repository clone, and `sudo python setup install`, when I launch the `/usr/local/bin/networkmgr` I get the following response:

/usr/local/bin/networkmgr 
Traceback (most recent call last):
  File "/usr/local/bin/networkmgr", line 4, in <module>
    __import__('pkg_resources').run_script('networkmgr==1.10', 'networkmgr')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 741, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'networkmgr'

My laptop runs Ghostbsd but updated to FreeBSD 10.4. Previous networkmgr was installed via pkg. 

Any idea?

Thanks, 

BR

**Comment by ericbsd** [comment]
I updated the readme https://github.com/GhostBSD/networkmgr/blob/master/README.md NetworkMgr is now using GTK3 and Python 3.6.
